// Generated by HostBridgeEmitter. Do not edit.
import Foundation
import InterpreterModels
import InterpreterVM

// MARK: - Foundation.NotificationCenter

@available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
public func Host_Foundation_u002E_NotificationCenter_publisher_u0028_for_u003A_object_u003A__u0029___Foundation_u002E_Notification_u002E_Name__Swift_u002E_Optional_u003C_Swift_u002E_AnyObject_u003E_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 3 else { throw VMError.typeError("NotificationCenter.publisher(for:object:) expects 2 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be NotificationCenter host") }
    let name: Foundation.Notification.Name = try vm.withHost(args[1], typeName: "Foundation.Notification.Name", as: Foundation.Notification.Name.self) { host in
        host
    }
    var object: AnyObject? = nil
    if case .nilValue = args[2] {
        object = nil
    } else {
        object = try vm.withHost(args[2], typeName: "AnyObject", as: AnyObject.self) { host in
            host
        }
    }
    let receiver = try vm.withHost(args[0], typeName: "NotificationCenter", as: Foundation.NotificationCenter.self) { host in
        host
    }
    let result = receiver.publisher(for: name, object: object)
    return .host(HostRef(box: makeOpaqueBox(result)), vm.hostTypeID(named: "NotificationCenter"))
}

@available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
public func HostDispatcher_Foundation_u002E_NotificationCenter_publisher_u0028_for_u003A_object_u003A__u0029___Foundation_u002E_Notification_u002E_Name__Swift_u002E_Optional_u003C_Swift_u002E_AnyObject_u003E_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be host") }
    if tid == vm.hostTypeID(named: "Foundation.NotificationCenter") {
        if #available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *) {
            return try Host_Foundation_u002E_NotificationCenter_publisher_u0028_for_u003A_object_u003A__u0029___Foundation_u002E_Notification_u002E_Name__Swift_u002E_Optional_u003C_Swift_u002E_AnyObject_u003E_(vm: &vm, args)
        } else {
            throw VMError.unsupported("NotificationCenter.publisher(for:object:) is not available on this platform")
        }
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Foundation.NotificationCenter (for: Foundation.Notification.Name, object: Swift.Optional<Swift.AnyObject>)",
    ] .joined(separator: "\n")
    throw VMError.typeError("NotificationCenter.publisher(for:object:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func HostAvailWrap_HostDispatcher_Foundation_u002E_NotificationCenter_publisher_u0028_for_u003A_object_u003A__u0029___Foundation_u002E_Notification_u002E_Name__Swift_u002E_Optional_u003C_Swift_u002E_AnyObject_u003E_(vm: inout VM, _ args: [Value]) throws -> Value {
    if #available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *) { return try HostDispatcher_Foundation_u002E_NotificationCenter_publisher_u0028_for_u003A_object_u003A__u0029___Foundation_u002E_Notification_u002E_Name__Swift_u002E_Optional_u003C_Swift_u002E_AnyObject_u003E_(vm: &vm, args) }
    throw VMError.unsupported("NotificationCenter.publisher(for:object:) is not available on this platform")
}

@available(macOS 26.0, iOS 26.0, tvOS 26.0, watchOS 26.0, visionOS 26.0, *)
public func Host_Foundation_u002E_NotificationCenter_removeObserver_u0028___u003A__u0029___Foundation_u002E_NotificationCenter_u002E_ObservationToken(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 2 else { throw VMError.typeError("NotificationCenter.removeObserver(_:) expects 1 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be NotificationCenter host") }
    let token: Foundation.NotificationCenter.ObservationToken = try vm.withHost(args[1], typeName: "Foundation.NotificationCenter.ObservationToken", as: Foundation.NotificationCenter.ObservationToken.self) { host in
        host
    }
    let receiver = try vm.withHost(args[0], typeName: "NotificationCenter", as: Foundation.NotificationCenter.self) { host in
        host
    }
    receiver.removeObserver(token)
    return .bool(true)
}

@available(macOS 26.0, iOS 26.0, tvOS 26.0, watchOS 26.0, visionOS 26.0, *)
public func HostDispatcher_Foundation_u002E_NotificationCenter_removeObserver_u0028___u003A__u0029___Foundation_u002E_NotificationCenter_u002E_ObservationToken(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be host") }
    if tid == vm.hostTypeID(named: "Foundation.NotificationCenter") {
        if #available(macOS 26.0, iOS 26.0, tvOS 26.0, watchOS 26.0, visionOS 26.0, *) {
            return try Host_Foundation_u002E_NotificationCenter_removeObserver_u0028___u003A__u0029___Foundation_u002E_NotificationCenter_u002E_ObservationToken(vm: &vm, args)
        } else {
            throw VMError.unsupported("NotificationCenter.removeObserver(_:) is not available on this platform")
        }
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Foundation.NotificationCenter (Foundation.NotificationCenter.ObservationToken)",
    ] .joined(separator: "\n")
    throw VMError.typeError("NotificationCenter.removeObserver(_:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func HostAvailWrap_HostDispatcher_Foundation_u002E_NotificationCenter_removeObserver_u0028___u003A__u0029___Foundation_u002E_NotificationCenter_u002E_ObservationToken(vm: inout VM, _ args: [Value]) throws -> Value {
    if #available(macOS 26.0, iOS 26.0, tvOS 26.0, watchOS 26.0, visionOS 26.0, *) { return try HostDispatcher_Foundation_u002E_NotificationCenter_removeObserver_u0028___u003A__u0029___Foundation_u002E_NotificationCenter_u002E_ObservationToken(vm: &vm, args) }
    throw VMError.unsupported("NotificationCenter.removeObserver(_:) is not available on this platform")
}

