// Generated by HostBridgeEmitter. Do not edit.
import Foundation
import InterpreterModels
import InterpreterVM

public func installFoundationHostBridges(into vm: inout VM) {
    vm.registerHostTypeAlias(canonical: "Foundation.Data", exported: "Data")
    vm.registerHostMethods(type: "Foundation.Data", methods: [
        "==(d1:d2:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data__u003D__u003D__u0028_d1_u003A_d2_u003A__u0029___op_eq_eq__Foundation_u002E_Data__Foundation_u002E_Data,
        "_copyContents(initializing:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data__copyContents_u0028_initializing_u003A__u0029___Swift_u002E_UnsafeMutableBufferPointer_u003C_Swift_u002E_UInt8_u003E_,
        "advanced(by:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_advanced_u0028_by_u003A__u0029___Swift_u002E_Int,
        "append(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_append_u0028___u003A__u0029___Foundation_u002E_Data,
        "append(_:count:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_append_u0028___u003A_count_u003A__u0029___Swift_u002E_UnsafePointer_u003C_Swift_u002E_UInt8_u003E___Swift_u002E_Int,
        "append(contentsOf:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_append_u0028_contentsOf_u003A__u0029___Swift_u002E_Array_u003C_Swift_u002E_UInt8_u003E_,
        "base64EncodedData(options:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_base64EncodedData_u0028_options_u003A__u0029___Foundation_u002E_Data_u002E_Base64EncodingOptions,
        "base64EncodedString(options:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_base64EncodedString_u0028_options_u003A__u0029___Foundation_u002E_Data_u002E_Base64EncodingOptions,
        "copyBytes(to:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_copyBytes_u0028_to_u003A__u0029___Swift_u002E_UnsafeMutableRawBufferPointer,
        "copyBytes(to:count:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_copyBytes_u0028_to_u003A_count_u003A__u0029___Swift_u002E_UnsafeMutablePointer_u003C_Swift_u002E_UInt8_u003E___Swift_u002E_Int,
        "copyBytes(to:from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_copyBytes_u0028_to_u003A_from_u003A__u0029___Swift_u002E_UnsafeMutablePointer_u003C_Swift_u002E_UInt8_u003E___Swift_u002E_Range_u003C_Foundation_u002E_Data_u002E_Index_u003E_,
        "encode(to:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder,
        "index(after:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_index_u0028_after_u003A__u0029___Foundation_u002E_Data_u002E_Index,
        "index(before:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_index_u0028_before_u003A__u0029___Foundation_u002E_Data_u002E_Index,
        "init()": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028__u0029_,
        "init(base64Encoded:options:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_base64Encoded_u003A_options_u003A__u0029___Swift_u002E_String__Foundation_u002E_Data_u002E_Base64DecodingOptions,
        "init(buffer:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_buffer_u003A__u0029___Swift_u002E_UnsafeBufferPointer_u003C_SourceType_u003E_,
        "init(bytes:count:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_bytes_u003A_count_u003A__u0029___Swift_u002E_UnsafeRawPointer__Swift_u002E_Int,
        "init(bytesNoCopy:count:deallocator:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_bytesNoCopy_u003A_count_u003A_deallocator_u003A__u0029___Swift_u002E_UnsafeMutableRawPointer__Swift_u002E_Int__Foundation_u002E_Data_u002E_Deallocator,
        "init(capacity:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_capacity_u003A__u0029___Swift_u002E_Int,
        "init(contentsOf:options:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_contentsOf_u003A_options_u003A__u0029___Foundation_u002E_URL__Foundation_u002E_Data_u002E_ReadingOptions,
        "init(count:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_count_u003A__u0029___Swift_u002E_Int,
        "init(from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_from_u003A__u0029___Swift_u002E_Decoder,
        "init(repeating:count:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_init_u0028_repeating_u003A_count_u003A__u0029___Swift_u002E_UInt8__Swift_u002E_Int,
        "makeIterator()": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_makeIterator_u0028__u0029_,
        "range(of:options:in:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_range_u0028_of_u003A_options_u003A_in_u003A__u0029___Foundation_u002E_Data__Foundation_u002E_Data_u002E_SearchOptions__Swift_u002E_Optional_u003C_Swift_u002E_Range_u003C_Foundation_u002E_Data_u002E_Index_u003E__u003E_,
        "replaceSubrange(_:with:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_replaceSubrange_u0028___u003A_with_u003A__u0029___Swift_u002E_Range_u003C_Foundation_u002E_Data_u002E_Index_u003E___Foundation_u002E_Data,
        "replaceSubrange(_:with:count:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_replaceSubrange_u0028___u003A_with_u003A_count_u003A__u0029___Swift_u002E_Range_u003C_Foundation_u002E_Data_u002E_Index_u003E___Swift_u002E_UnsafeRawPointer__Swift_u002E_Int,
        "reserveCapacity(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_reserveCapacity_u0028___u003A__u0029___Swift_u002E_Int,
        "resetBytes(in:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_resetBytes_u0028_in_u003A__u0029___Swift_u002E_Range_u003C_Foundation_u002E_Data_u002E_Index_u003E_,
        "subdata(in:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_subdata_u0028_in_u003A__u0029___Swift_u002E_Range_u003C_Foundation_u002E_Data_u002E_Index_u003E_,
        "write(to:options:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Data_write_u0028_to_u003A_options_u003A__u0029___Foundation_u002E_URL__Foundation_u002E_Data_u002E_WritingOptions,
    ])
    vm.registerHostProperty(type: "Foundation.Data", name: "count", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_count, set: HostAvailWrap_HostSetter_Foundation_u002E_Data_count)
    vm.registerHostProperty(type: "Foundation.Data", name: "customMirror", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_customMirror)
    vm.registerHostProperty(type: "Foundation.Data", name: "debugDescription", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_debugDescription)
    vm.registerHostProperty(type: "Foundation.Data", name: "description", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_description)
    vm.registerHostProperty(type: "Foundation.Data", name: "endIndex", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_endIndex)
    vm.registerHostProperty(type: "Foundation.Data", name: "hashValue", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_hashValue)
    vm.registerHostProperty(type: "Foundation.Data", name: "indices", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_indices)
    vm.registerHostProperty(type: "Foundation.Data", name: "regions", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_regions)
    vm.registerHostProperty(type: "Foundation.Data", name: "startIndex", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Data_startIndex)
    vm.registerHostTypeAlias(canonical: "Foundation.Date", exported: "Date")
    vm.registerHostMethods(type: "Foundation.Date", methods: [
        "+(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date__u002B__u0028_lhs_u003A_rhs_u003A__u0029___op_plus__Foundation_u002E_Date__Foundation_u002E_TimeInterval,
        "-(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date__u002D__u0028_lhs_u003A_rhs_u003A__u0029___op_minus__Foundation_u002E_Date__Foundation_u002E_TimeInterval,
        "<(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date__u003C__u0028_lhs_u003A_rhs_u003A__u0029___op_lt__Foundation_u002E_Date__Foundation_u002E_Date,
        "==(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Foundation_u002E_Date__Foundation_u002E_Date,
        ">(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date__u003E__u0028_lhs_u003A_rhs_u003A__u0029___op_gt__Foundation_u002E_Date__Foundation_u002E_Date,
        "ISO8601Format(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_ISO8601Format_u0028___u003A__u0029___Foundation_u002E_Date_u002E_ISO8601FormatStyle,
        "addTimeInterval(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_addTimeInterval_u0028___u003A__u0029___Foundation_u002E_TimeInterval,
        "addingTimeInterval(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_addingTimeInterval_u0028___u003A__u0029___Foundation_u002E_TimeInterval,
        "advanced(by:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_advanced_u0028_by_u003A__u0029___Foundation_u002E_TimeInterval,
        "compare(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_compare_u0028___u003A__u0029___Foundation_u002E_Date,
        "description(with:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_description_u0028_with_u003A__u0029___Swift_u002E_Optional_u003C_Foundation_u002E_Locale_u003E_,
        "distance(to:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_distance_u0028_to_u003A__u0029___Foundation_u002E_Date,
        "encode(to:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder,
        "formatted()": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_formatted_u0028__u0029_,
        "formatted(date:time:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_formatted_u0028_date_u003A_time_u003A__u0029___Foundation_u002E_Date_u002E_FormatStyle_u002E_DateStyle__Foundation_u002E_Date_u002E_FormatStyle_u002E_TimeStyle,
        "init()": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_init_u0028__u0029_,
        "init(from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_init_u0028_from_u003A__u0029___Swift_u002E_Decoder,
        "init(timeInterval:since:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_init_u0028_timeInterval_u003A_since_u003A__u0029___Foundation_u002E_TimeInterval__Foundation_u002E_Date,
        "init(timeIntervalSince1970:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_init_u0028_timeIntervalSince1970_u003A__u0029___Foundation_u002E_TimeInterval,
        "init(timeIntervalSinceNow:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_init_u0028_timeIntervalSinceNow_u003A__u0029___Foundation_u002E_TimeInterval,
        "init(timeIntervalSinceReferenceDate:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_init_u0028_timeIntervalSinceReferenceDate_u003A__u0029___Foundation_u002E_TimeInterval,
        "timeIntervalSince(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Date_timeIntervalSince_u0028___u003A__u0029___Foundation_u002E_Date,
    ])
    vm.registerHostProperty(type: "Foundation.Date", name: "customMirror", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_customMirror)
    vm.registerHostProperty(type: "Foundation.Date", name: "customPlaygroundQuickLook", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_customPlaygroundQuickLook)
    vm.registerHostProperty(type: "Foundation.Date", name: "debugDescription", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_debugDescription)
    vm.registerHostProperty(type: "Foundation.Date", name: "description", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_description)
    vm.registerHostProperty(type: "Foundation.Date", name: "hashValue", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_hashValue)
    vm.registerHostProperty(type: "Foundation.Date", name: "now", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_now)
    vm.registerHostProperty(type: "Foundation.Date", name: "timeIntervalSince1970", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_timeIntervalSince1970)
    vm.registerHostProperty(type: "Foundation.Date", name: "timeIntervalSinceNow", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_timeIntervalSinceNow)
    vm.registerHostProperty(type: "Foundation.Date", name: "timeIntervalSinceReferenceDate", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Date_timeIntervalSinceReferenceDate)
    vm.registerHostTypeAlias(canonical: "Foundation.DateComponents", exported: "DateComponents")
    vm.registerHostMethods(type: "Foundation.DateComponents", methods: [
        "==(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Foundation_u002E_DateComponents__Foundation_u002E_DateComponents,
        "encode(to:)": HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder,
        "init(calendar:timeZone:era:year:month:day:hour:minute:second:nanosecond:weekday:weekdayOrdinal:quarter:weekOfMonth:weekOfYear:yearForWeekOfYear:)": HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_init_u0028_calendar_u003A_timeZone_u003A_era_u003A_year_u003A_month_u003A_day_u003A_hour_u003A_minute_u003A_second_u003A_nanosecond_u003A_weekday_u003A_weekdayOrdinal_u003A_quarter_u003A_weekOfMonth_u003A_weekOfYear_u003A_yearForWeekOfYear_u003A__u0029___Swift_u002E_Optional_u003C_Foundation_u002E_Calendar_u003E___Swift_u002E_Optional_u003C_Foundation_u002E_TimeZone_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E_,
        "init(from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_init_u0028_from_u003A__u0029___Swift_u002E_Decoder,
        "isValidDate(in:)": HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_isValidDate_u0028_in_u003A__u0029___Foundation_u002E_Calendar,
        "setValue(_:for:)": HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_setValue_u0028___u003A_for_u003A__u0029___Swift_u002E_Optional_u003C_Swift_u002E_Int_u003E___Foundation_u002E_Calendar_u002E_Component,
        "value(for:)": HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_value_u0028_for_u003A__u0029___Foundation_u002E_Calendar_u002E_Component,
    ])
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "calendar", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_calendar, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_calendar)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "customMirror", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_customMirror)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "date", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_date)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "day", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_day, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_day)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "dayOfYear", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_dayOfYear, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_dayOfYear)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "debugDescription", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_debugDescription)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "description", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_description)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "era", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_era, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_era)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "hashValue", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_hashValue)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "hour", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_hour, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_hour)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "isLeapMonth", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_isLeapMonth, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_isLeapMonth)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "isRepeatedDay", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_isRepeatedDay, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_isRepeatedDay)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "isValidDate", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_isValidDate)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "minute", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_minute, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_minute)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "month", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_month, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_month)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "nanosecond", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_nanosecond, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_nanosecond)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "quarter", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_quarter, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_quarter)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "second", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_second, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_second)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "timeZone", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_timeZone, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_timeZone)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "weekOfMonth", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_weekOfMonth, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_weekOfMonth)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "weekOfYear", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_weekOfYear, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_weekOfYear)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "weekday", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_weekday, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_weekday)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "weekdayOrdinal", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_weekdayOrdinal, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_weekdayOrdinal)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "year", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_year, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_year)
    vm.registerHostProperty(type: "Foundation.DateComponents", name: "yearForWeekOfYear", get: HostAvailWrap_HostDispatcher_Foundation_u002E_DateComponents_yearForWeekOfYear, set: HostAvailWrap_HostSetter_Foundation_u002E_DateComponents_yearForWeekOfYear)
    vm.registerHostTypeAlias(canonical: "Foundation.Locale", exported: "Locale")
    vm.registerHostMethods(type: "Foundation.Locale", methods: [
        "==(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Foundation_u002E_Locale__Foundation_u002E_Locale,
        "canonicalIdentifier(from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_canonicalIdentifier_u0028_from_u003A__u0029___Swift_u002E_String,
        "canonicalLanguageIdentifier(from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_canonicalLanguageIdentifier_u0028_from_u003A__u0029___Swift_u002E_String,
        "characterDirection(forLanguage:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_characterDirection_u0028_forLanguage_u003A__u0029___Swift_u002E_String,
        "components(fromIdentifier:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_components_u0028_fromIdentifier_u003A__u0029___Swift_u002E_String,
        "encode(to:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder,
        "identifier(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_identifier_u0028___u003A__u0029___Foundation_u002E_Locale_u002E_IdentifierType,
        "identifier(_:from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_identifier_u0028___u003A_from_u003A__u0029___Foundation_u002E_Locale_u002E_IdentifierType__Swift_u002E_String,
        "identifier(fromComponents:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_identifier_u0028_fromComponents_u003A__u0029___Swift_u002E_Dictionary_u003C_Swift_u002E_String_u002C_Swift_u002E_String_u003E_,
        "identifier(fromWindowsLocaleCode:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_identifier_u0028_fromWindowsLocaleCode_u003A__u0029___Swift_u002E_Int,
        "init(components:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_init_u0028_components_u003A__u0029___Foundation_u002E_Locale_u002E_Components,
        "init(from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_init_u0028_from_u003A__u0029___Swift_u002E_Decoder,
        "init(identifier:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_init_u0028_identifier_u003A__u0029___Swift_u002E_String,
        "init(languageCode:script:languageRegion:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_init_u0028_languageCode_u003A_script_u003A_languageRegion_u003A__u0029___Swift_u002E_Optional_u003C_Foundation_u002E_Locale_u002E_LanguageCode_u003E___Swift_u002E_Optional_u003C_Foundation_u002E_Locale_u002E_Script_u003E___Swift_u002E_Optional_u003C_Foundation_u002E_Locale_u002E_Region_u003E_,
        "init(languageComponents:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_init_u0028_languageComponents_u003A__u0029___Foundation_u002E_Locale_u002E_Language_u002E_Components,
        "lineDirection(forLanguage:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_lineDirection_u0028_forLanguage_u003A__u0029___Swift_u002E_String,
        "localizedString(for:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_for_u003A__u0029___Foundation_u002E_Calendar_u002E_Identifier,
        "localizedString(forCollationIdentifier:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forCollationIdentifier_u003A__u0029___Swift_u002E_String,
        "localizedString(forCollatorIdentifier:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forCollatorIdentifier_u003A__u0029___Swift_u002E_String,
        "localizedString(forCurrencyCode:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forCurrencyCode_u003A__u0029___Swift_u002E_String,
        "localizedString(forIdentifier:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forIdentifier_u003A__u0029___Swift_u002E_String,
        "localizedString(forLanguageCode:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forLanguageCode_u003A__u0029___Swift_u002E_String,
        "localizedString(forRegionCode:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forRegionCode_u003A__u0029___Swift_u002E_String,
        "localizedString(forScriptCode:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forScriptCode_u003A__u0029___Swift_u002E_String,
        "localizedString(forVariantCode:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_localizedString_u0028_forVariantCode_u003A__u0029___Swift_u002E_String,
        "windowsLocaleCode(fromIdentifier:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_windowsLocaleCode_u0028_fromIdentifier_u003A__u0029___Swift_u002E_String,
    ])
    vm.registerHostProperty(type: "Foundation.Locale", name: "alternateQuotationBeginDelimiter", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_alternateQuotationBeginDelimiter)
    vm.registerHostProperty(type: "Foundation.Locale", name: "alternateQuotationEndDelimiter", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_alternateQuotationEndDelimiter)
    vm.registerHostProperty(type: "Foundation.Locale", name: "autoupdatingCurrent", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_autoupdatingCurrent)
    vm.registerHostProperty(type: "Foundation.Locale", name: "availableIdentifiers", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_availableIdentifiers)
    vm.registerHostProperty(type: "Foundation.Locale", name: "availableNumberingSystems", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_availableNumberingSystems)
    vm.registerHostProperty(type: "Foundation.Locale", name: "calendar", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_calendar)
    vm.registerHostProperty(type: "Foundation.Locale", name: "collation", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_collation)
    vm.registerHostProperty(type: "Foundation.Locale", name: "collationIdentifier", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_collationIdentifier)
    vm.registerHostProperty(type: "Foundation.Locale", name: "collatorIdentifier", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_collatorIdentifier)
    vm.registerHostProperty(type: "Foundation.Locale", name: "commonISOCurrencyCodes", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_commonISOCurrencyCodes)
    vm.registerHostProperty(type: "Foundation.Locale", name: "currency", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_currency)
    vm.registerHostProperty(type: "Foundation.Locale", name: "currencyCode", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_currencyCode)
    vm.registerHostProperty(type: "Foundation.Locale", name: "currencySymbol", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_currencySymbol)
    vm.registerHostProperty(type: "Foundation.Locale", name: "current", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_current)
    vm.registerHostProperty(type: "Foundation.Locale", name: "customMirror", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_customMirror)
    vm.registerHostProperty(type: "Foundation.Locale", name: "debugDescription", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_debugDescription)
    vm.registerHostProperty(type: "Foundation.Locale", name: "decimalSeparator", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_decimalSeparator)
    vm.registerHostProperty(type: "Foundation.Locale", name: "description", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_description)
    vm.registerHostProperty(type: "Foundation.Locale", name: "exemplarCharacterSet", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_exemplarCharacterSet)
    vm.registerHostProperty(type: "Foundation.Locale", name: "firstDayOfWeek", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_firstDayOfWeek)
    vm.registerHostProperty(type: "Foundation.Locale", name: "groupingSeparator", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_groupingSeparator)
    vm.registerHostProperty(type: "Foundation.Locale", name: "hashValue", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_hashValue)
    vm.registerHostProperty(type: "Foundation.Locale", name: "hourCycle", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_hourCycle)
    vm.registerHostProperty(type: "Foundation.Locale", name: "identifier", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_identifier)
    vm.registerHostProperty(type: "Foundation.Locale", name: "isoCurrencyCodes", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_isoCurrencyCodes)
    vm.registerHostProperty(type: "Foundation.Locale", name: "isoLanguageCodes", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_isoLanguageCodes)
    vm.registerHostProperty(type: "Foundation.Locale", name: "isoRegionCodes", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_isoRegionCodes)
    vm.registerHostProperty(type: "Foundation.Locale", name: "language", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_language)
    vm.registerHostProperty(type: "Foundation.Locale", name: "languageCode", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_languageCode)
    vm.registerHostProperty(type: "Foundation.Locale", name: "measurementSystem", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_measurementSystem)
    vm.registerHostProperty(type: "Foundation.Locale", name: "numberingSystem", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_numberingSystem)
    vm.registerHostProperty(type: "Foundation.Locale", name: "preferredLanguages", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_preferredLanguages)
    vm.registerHostProperty(type: "Foundation.Locale", name: "preferredLocales", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_preferredLocales)
    vm.registerHostProperty(type: "Foundation.Locale", name: "quotationBeginDelimiter", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_quotationBeginDelimiter)
    vm.registerHostProperty(type: "Foundation.Locale", name: "quotationEndDelimiter", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_quotationEndDelimiter)
    vm.registerHostProperty(type: "Foundation.Locale", name: "region", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_region)
    vm.registerHostProperty(type: "Foundation.Locale", name: "regionCode", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_regionCode)
    vm.registerHostProperty(type: "Foundation.Locale", name: "scriptCode", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_scriptCode)
    vm.registerHostProperty(type: "Foundation.Locale", name: "subdivision", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_subdivision)
    vm.registerHostProperty(type: "Foundation.Locale", name: "timeZone", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_timeZone)
    vm.registerHostProperty(type: "Foundation.Locale", name: "usesMetricSystem", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_usesMetricSystem)
    vm.registerHostProperty(type: "Foundation.Locale", name: "variant", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_variant)
    vm.registerHostProperty(type: "Foundation.Locale", name: "variantCode", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Locale_variantCode)
    vm.registerHostTypeAlias(canonical: "Foundation.Notification", exported: "Notification")
    vm.registerHostMethods(type: "Foundation.Notification", methods: [
        "==(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Notification__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Foundation_u002E_Notification__Foundation_u002E_Notification,
        "init(name:object:userInfo:)": HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_init_u0028_name_u003A_object_u003A_userInfo_u003A__u0029___Foundation_u002E_Notification_u002E_Name__Swift_u002E_Optional_u003C_Swift_u002E_Any_u003E___Swift_u002E_Optional_u003C_Swift_u002E_Dictionary_u003C_Swift_u002E_AnyHashable_u002C_Swift_u002E_Any_u003E__u003E_,
    ])
    vm.registerHostProperty(type: "Foundation.Notification", name: "customMirror", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_customMirror)
    vm.registerHostProperty(type: "Foundation.Notification", name: "debugDescription", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_debugDescription)
    vm.registerHostProperty(type: "Foundation.Notification", name: "description", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_description)
    vm.registerHostProperty(type: "Foundation.Notification", name: "hashValue", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_hashValue)
    vm.registerHostProperty(type: "Foundation.Notification", name: "name", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_name, set: HostAvailWrap_HostSetter_Foundation_u002E_Notification_name)
    vm.registerHostProperty(type: "Foundation.Notification", name: "object", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_object, set: HostAvailWrap_HostSetter_Foundation_u002E_Notification_object)
    vm.registerHostProperty(type: "Foundation.Notification", name: "userInfo", get: HostAvailWrap_HostDispatcher_Foundation_u002E_Notification_userInfo, set: HostAvailWrap_HostSetter_Foundation_u002E_Notification_userInfo)
    vm.registerHostTypeAlias(canonical: "Foundation.NotificationCenter", exported: "NotificationCenter")
    vm.registerHostMethods(type: "Foundation.NotificationCenter", methods: [
        "publisher(for:object:)": HostAvailWrap_HostDispatcher_Foundation_u002E_NotificationCenter_publisher_u0028_for_u003A_object_u003A__u0029___Foundation_u002E_Notification_u002E_Name__Swift_u002E_Optional_u003C_Swift_u002E_AnyObject_u003E_,
        "removeObserver(_:)": HostAvailWrap_HostDispatcher_Foundation_u002E_NotificationCenter_removeObserver_u0028___u003A__u0029___Foundation_u002E_NotificationCenter_u002E_ObservationToken,
    ])
    vm.registerHostTypeAlias(canonical: "Foundation.TimeZone", exported: "TimeZone")
    vm.registerHostMethods(type: "Foundation.TimeZone", methods: [
        "==(lhs:rhs:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Foundation_u002E_TimeZone__Foundation_u002E_TimeZone,
        "abbreviation(for:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_abbreviation_u0028_for_u003A__u0029___Foundation_u002E_Date,
        "daylightSavingTimeOffset(for:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_daylightSavingTimeOffset_u0028_for_u003A__u0029___Foundation_u002E_Date,
        "encode(to:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder,
        "init(abbreviation:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_init_u0028_abbreviation_u003A__u0029___Swift_u002E_String,
        "init(from:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_init_u0028_from_u003A__u0029___Swift_u002E_Decoder,
        "init(identifier:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_init_u0028_identifier_u003A__u0029___Swift_u002E_String,
        "init(secondsFromGMT:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_init_u0028_secondsFromGMT_u003A__u0029___Swift_u002E_Int,
        "isDaylightSavingTime(for:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_isDaylightSavingTime_u0028_for_u003A__u0029___Foundation_u002E_Date,
        "localizedName(for:locale:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_localizedName_u0028_for_u003A_locale_u003A__u0029___Foundation_u002E_TimeZone_u002E_NameStyle__Swift_u002E_Optional_u003C_Foundation_u002E_Locale_u003E_,
        "nextDaylightSavingTimeTransition(after:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_nextDaylightSavingTimeTransition_u0028_after_u003A__u0029___Foundation_u002E_Date,
        "secondsFromGMT(for:)": HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_secondsFromGMT_u0028_for_u003A__u0029___Foundation_u002E_Date,
    ])
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "abbreviationDictionary", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_abbreviationDictionary, set: HostAvailWrap_HostSetter_Foundation_u002E_TimeZone_abbreviationDictionary)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "autoupdatingCurrent", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_autoupdatingCurrent)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "current", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_current)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "customMirror", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_customMirror)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "debugDescription", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_debugDescription)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "description", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_description)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "gmt", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_gmt)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "hashValue", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_hashValue)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "identifier", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_identifier)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "knownTimeZoneIdentifiers", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_knownTimeZoneIdentifiers)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "nextDaylightSavingTimeTransition", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_nextDaylightSavingTimeTransition)
    vm.registerHostProperty(type: "Foundation.TimeZone", name: "timeZoneDataVersion", get: HostAvailWrap_HostDispatcher_Foundation_u002E_TimeZone_timeZoneDataVersion)
}

public let foundationHostBridgeRegistration: Void = {
    VM.registerHostBridgeInstaller(installFoundationHostBridges(into:))
    return ()
}()
