// Generated by HostBridgeEmitter. Do not edit.
import Foundation
import InterpreterModels
import InterpreterVM

// MARK: - Swift.Bool

public func Host_Swift_u002E_Bool__u0021__u0028_a_u003A__u0029___op_bang__Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 2 else { throw VMError.typeError("Bool.!(a:) expects 1 args") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be Bool metatype") }
    let a = try args[1].expectBool("a")
    let result = !a
    return .bool(result)
}

public func HostDispatcher_Swift_u002E_Bool__u0021__u0028_a_u003A__u0029___op_bang__Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be metatype") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool__u0021__u0028_a_u003A__u0029___op_bang__Swift_u002E_Bool(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool (a: Swift.Bool)",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.!(a:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool__u0021__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_bang_eq__Swift_u002E_Bool__Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 3 else { throw VMError.typeError("Bool.!=(lhs:rhs:) expects 2 args") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be Bool metatype") }
    let lhs = try args[1].expectBool("lhs")
    let rhs = try args[2].expectBool("rhs")
    let result = lhs != rhs
    return .bool(result)
}

public func HostDispatcher_Swift_u002E_Bool__u0021__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_bang_eq__Swift_u002E_Bool__Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be metatype") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool__u0021__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_bang_eq__Swift_u002E_Bool__Swift_u002E_Bool(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool (lhs: Swift.Bool, rhs: Swift.Bool)",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.!=(lhs:rhs:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Swift_u002E_Bool__Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 3 else { throw VMError.typeError("Bool.==(lhs:rhs:) expects 2 args") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be Bool metatype") }
    let lhs = try args[1].expectBool("lhs")
    let rhs = try args[2].expectBool("rhs")
    let result = lhs == rhs
    return .bool(result)
}

public func HostDispatcher_Swift_u002E_Bool__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Swift_u002E_Bool__Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be metatype") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool__u003D__u003D__u0028_lhs_u003A_rhs_u003A__u0029___op_eq_eq__Swift_u002E_Bool__Swift_u002E_Bool(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool (lhs: Swift.Bool, rhs: Swift.Bool)",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.==(lhs:rhs:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool__rawHashValue_u0028_seed_u003A__u0029___Swift_u002E_Int(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 2 else { throw VMError.typeError("Bool._rawHashValue(seed:) expects 1 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    let seed = try args[1].expectInt("seed")
    let receiver = try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { host in
        host
    }
    let result = receiver._rawHashValue(seed: seed)
    return .int(result)
}

public func HostDispatcher_Swift_u002E_Bool__rawHashValue_u0028_seed_u003A__u0029___Swift_u002E_Int(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be host") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool__rawHashValue_u0028_seed_u003A__u0029___Swift_u002E_Int(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool (seed: Swift.Int)",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool._rawHashValue(seed:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 2 else { throw VMError.typeError("Bool.encode(to:) expects 1 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    let encoder: Swift.Encoder = try vm.withHost(args[1], typeName: "Swift.Encoder", as: Swift.Encoder.self) { host in
        host
    }
    let receiver = try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { host in
        host
    }
    try receiver.encode(to: encoder)
    return .bool(true)
}

public func HostDispatcher_Swift_u002E_Bool_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be host") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool_encode_u0028_to_u003A__u0029___Swift_u002E_Encoder(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool (to: Swift.Encoder)",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.encode(to:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_init_u0028__u0029_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Bool.init() expects 0 args") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be Bool metatype") }
    let result = Swift.Bool()
    return .bool(result)
}

public func HostDispatcher_Swift_u002E_Bool_init_u0028__u0029_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be metatype") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool_init_u0028__u0029_(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool ()",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.init() has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_init_u0028_booleanLiteral_u003A__u0029___Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 2 else { throw VMError.typeError("Bool.init(booleanLiteral:) expects 1 args") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be Bool metatype") }
    let value = try args[1].expectBool("value")
    let result = Swift.Bool(booleanLiteral: value)
    return .bool(result)
}

public func HostDispatcher_Swift_u002E_Bool_init_u0028_booleanLiteral_u003A__u0029___Swift_u002E_Bool(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be metatype") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool_init_u0028_booleanLiteral_u003A__u0029___Swift_u002E_Bool(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool (booleanLiteral: Swift.Bool)",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.init(booleanLiteral:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_init_u0028_from_u003A__u0029___Swift_u002E_Decoder(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 2 else { throw VMError.typeError("Bool.init(from:) expects 1 args") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be Bool metatype") }
    let decoder: Swift.Decoder = try vm.withHost(args[1], typeName: "Swift.Decoder", as: Swift.Decoder.self) { host in
        host
    }
    let result = try Swift.Bool(from: decoder)
    return .bool(result)
}

public func HostDispatcher_Swift_u002E_Bool_init_u0028_from_u003A__u0029___Swift_u002E_Decoder(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be metatype") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool_init_u0028_from_u003A__u0029___Swift_u002E_Decoder(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool (from: Swift.Decoder)",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.init(from:) has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_random_u0028__u0029_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Bool.random() expects 0 args") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be Bool metatype") }
    let result = Swift.Bool.random()
    return .bool(result)
}

public func HostDispatcher_Swift_u002E_Bool_random_u0028__u0029_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .metatype(tid) = args[0] else { throw VMError.typeError("receiver must be metatype") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool_random_u0028__u0029_(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool ()",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.random() has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_toggle_u0028__u0029_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Bool.toggle() expects 0 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    return try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { receiver in
        receiver.toggle()
        return args[0]
    }
}

public func HostDispatcher_Swift_u002E_Bool_toggle_u0028__u0029_(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be host") }
    if tid == vm.hostTypeID(named: "Swift.Bool") {
        return try Host_Swift_u002E_Bool_toggle_u0028__u0029_(vm: &vm, args)
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
        "  - Swift.Bool ()",
    ] .joined(separator: "\n")
    throw VMError.typeError("Bool.toggle() has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool__cVarArgEncoding_instance(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Swift.Bool._cVarArgEncoding expects 0 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    let receiver = try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { host in
        host
    }
    let result = receiver._cVarArgEncoding
    var result_value_elements: [Value] = []
    result_value_elements.reserveCapacity(result.count)
    for result_value_element in result {
        result_value_elements.append(.int(result_value_element))
    }
    let result_value_arrayBox = ArrBox(result_value_elements)
    return .array(result_value_arrayBox)
}

public func HostDispatcher_Swift_u002E_Bool__cVarArgEncoding(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    let tid: TypeID
    switch args[0] {
    case .host(_, let receiverTid): tid = receiverTid
    case .metatype(let receiverTid): tid = receiverTid
    default: throw VMError.typeError("receiver must be host or metatype")
    }
    if tid == vm.hostTypeID(named: "Bool") {
        switch args[0] {
        case .host: return try Host_Swift_u002E_Bool__cVarArgEncoding_instance(vm: &vm, args)
        default: break
        }
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
    "  - Swift.Bool ()",
] .joined(separator: "\n")
    throw VMError.typeError("Getter for Swift.Bool._cVarArgEncoding has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_customMirror_instance(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Swift.Bool.customMirror expects 0 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    let receiver = try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { host in
        host
    }
    let result = receiver.customMirror
    return .host(HostRef(box: makeOpaqueBox(result)), vm.hostTypeID(named: "Bool"))
}

public func HostDispatcher_Swift_u002E_Bool_customMirror(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    let tid: TypeID
    switch args[0] {
    case .host(_, let receiverTid): tid = receiverTid
    case .metatype(let receiverTid): tid = receiverTid
    default: throw VMError.typeError("receiver must be host or metatype")
    }
    if tid == vm.hostTypeID(named: "Bool") {
        switch args[0] {
        case .host: return try Host_Swift_u002E_Bool_customMirror_instance(vm: &vm, args)
        default: break
        }
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
    "  - Swift.Bool ()",
] .joined(separator: "\n")
    throw VMError.typeError("Getter for Swift.Bool.customMirror has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

@available(*, deprecated, message: "Bool.customPlaygroundQuickLook will be removed in a future Swift version")
public func Host_Swift_u002E_Bool_customPlaygroundQuickLook_instance(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Swift.Bool.customPlaygroundQuickLook expects 0 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    let receiver = try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { host in
        host
    }
    let result = receiver.customPlaygroundQuickLook
    return .host(HostRef(box: makeOpaqueBox(result)), vm.hostTypeID(named: "Bool"))
}

@available(*, deprecated, message: "Bool.customPlaygroundQuickLook will be removed in a future Swift version")
public func HostDispatcher_Swift_u002E_Bool_customPlaygroundQuickLook(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    let tid: TypeID
    switch args[0] {
    case .host(_, let receiverTid): tid = receiverTid
    case .metatype(let receiverTid): tid = receiverTid
    default: throw VMError.typeError("receiver must be host or metatype")
    }
    if tid == vm.hostTypeID(named: "Bool") {
        switch args[0] {
        case .host:
            if true { return try Host_Swift_u002E_Bool_customPlaygroundQuickLook_instance(vm: &vm, args) }
            else { throw VMError.unsupported("Getter for Swift.Bool.customPlaygroundQuickLook is not available on this platform") }
        default: break
        }
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
    "  - Swift.Bool ()",
] .joined(separator: "\n")
    throw VMError.typeError("Getter for Swift.Bool.customPlaygroundQuickLook has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func HostAvailWrap_HostDispatcher_Swift_u002E_Bool_customPlaygroundQuickLook(vm: inout VM, _ args: [Value]) throws -> Value {
    if true { return try HostDispatcher_Swift_u002E_Bool_customPlaygroundQuickLook(vm: &vm, args) }
    throw VMError.unsupported("Getter for Swift.Bool.customPlaygroundQuickLook is not available on this platform")
}

public func Host_Swift_u002E_Bool_description_instance(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Swift.Bool.description expects 0 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    let receiver = try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { host in
        host
    }
    let result = receiver.description
    return .string(result)
}

public func HostDispatcher_Swift_u002E_Bool_description(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    let tid: TypeID
    switch args[0] {
    case .host(_, let receiverTid): tid = receiverTid
    case .metatype(let receiverTid): tid = receiverTid
    default: throw VMError.typeError("receiver must be host or metatype")
    }
    if tid == vm.hostTypeID(named: "Bool") {
        switch args[0] {
        case .host: return try Host_Swift_u002E_Bool_description_instance(vm: &vm, args)
        default: break
        }
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
    "  - Swift.Bool ()",
] .joined(separator: "\n")
    throw VMError.typeError("Getter for Swift.Bool.description has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

public func Host_Swift_u002E_Bool_hashValue_instance(vm: inout VM, _ args: [Value]) throws -> Value {
    guard args.count == 1 else { throw VMError.typeError("Swift.Bool.hashValue expects 0 args") }
    guard case let .host(_, tid) = args[0] else { throw VMError.typeError("receiver must be Bool host") }
    let receiver = try vm.withHost(args[0], typeName: "Bool", as: Swift.Bool.self) { host in
        host
    }
    let result = receiver.hashValue
    return .int(result)
}

public func HostDispatcher_Swift_u002E_Bool_hashValue(vm: inout VM, _ args: [Value]) throws -> Value {
    guard !args.isEmpty else { throw VMError.typeError("missing receiver") }
    let tid: TypeID
    switch args[0] {
    case .host(_, let receiverTid): tid = receiverTid
    case .metatype(let receiverTid): tid = receiverTid
    default: throw VMError.typeError("receiver must be host or metatype")
    }
    if tid == vm.hostTypeID(named: "Bool") {
        switch args[0] {
        case .host: return try Host_Swift_u002E_Bool_hashValue_instance(vm: &vm, args)
        default: break
        }
    }
    let receiverName = vm.debugTypeName(tid)
    let supported = [
    "  - Swift.Bool ()",
] .joined(separator: "\n")
    throw VMError.typeError("Getter for Swift.Bool.hashValue has no specialization for receiver \(receiverName). Supported specializations:\(supported)")
}

